### ISSUE TITLE
Cant inject javascipt code into webview.

### ISSUE THREAD

**Issue by isahin1997** [nmoschkin/MAUIWebViewExample#2]
Normally it would be possible to use the EvaluateJavaScriptAsync method to execute javascript code in the webview. I can't seem to get this work with this example. Do you maybe have a quick idea to implement this feature into this project?

**Comment by nmoschkin** [comment]
Yes, as noted in my original answer, this is a 100% pure re-implementation of WebView, so any native features that you want to add to the new webview will have to be re-implemented.

**Comment by nmoschkin** [comment]
Out of scope.

**Comment by nmoschkin** [comment]
Okay. I went ahead and did this because people kept asking.  I thought it would have been relatively simple for others to implement on their own.
